services:
    frontend:
        image: patient-transfer-frontend-dev
        build:
            context: .
            dockerfile: frontend/patient-transfer-app/Dockerfile.watch
        volumes:
            - ./frontend:/frontend/
            - frontend-tmp:/frontend/patient-transfer-app/node_modules
        ports:
            - 8080:8080

    backend:
        image: patient-transfer-backend-dev
        build:
            context: .
            dockerfile: backend/PatientTransfer.Server/Dockerfile.watch
        volumes:
            - ./backend:/backend/
            - backend-tmp-bin:/backend/PatientTransfer.Server/bin
            - backend-tmp-obj:/backend/PatientTransfer.Server/obj
        ports:
            - 8000:8000

volumes:
    frontend-tmp:
        driver: local
        driver_opts:
            type: tmpfs
            device: tmpfs
    backend-tmp-bin:
        driver: local
        driver_opts:
            type: tmpfs
            device: tmpfs
    backend-tmp-obj:
        driver: local
        driver_opts:
            type: tmpfs
            device: tmpfs